version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "kafka.payment.in:1:1,kafka.payment.in2:1:1,kafka.payment.out:1:1:compact"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
#  ibmmq:
#    image: ibmcom/mq:latest
#    ports:
#      - "1414:1414"
#    environment:
#      LICENSE: "accept"
#      MQ_QMGR_NAME: "QM1"
#      MQ_APP_PASSWORD: "passw0rd"
#    volumes:
#      - /Users/venkatarao/IdeaProjects/spring-integregation-hub/mq1data:/mnt/mqm
  mqseries:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: localhost
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    container_name: mqserver
    stdin_open: true
    tty: true
    restart: always
  springintegrationhub:
    image: springintegrationhub:latest
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
      - mqseries

